# Generated by Django 2.2 on 2020-02-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreads_app', '0002_auto_20200220_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Alias',
            new_name='alias',
        ),
    ]
