# Generated by Django 2.2 on 2020-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreads_app', '0003_auto_20200220_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
