# Generated by Django 2.2 on 2020-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreads_app', '0004_auto_20200221_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isreview',
            field=models.BooleanField(default=False),
        ),
    ]
