# Generated by Django 2.2 on 2020-02-13 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0003_auto_20200213_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='network',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='releasedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
